# Generated by Django 2.2.7 on 2019-11-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qoute',
            name='auther',
            field=models.CharField(default='', max_length=50),
        ),
    ]
