# Generated by Django 2.2.7 on 2019-11-16 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_qoute_auther'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Qoute',
            new_name='Quote',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='auther',
            new_name='author',
        ),
    ]
